language: ruby
sudo: false
rvm:
  - 2.3.0
  - 2.2.4
gemfile:
  - gemfiles/activerecord-41.gemfile
  - gemfiles/activerecord-42.gemfile
  - gemfiles/activerecord-502.gemfile
  - gemfiles/activerecord-50.gemfile
